#Declare constants in a separate file called constant.py
import os
PI = 3.14
GRAVITY = 9.8
PROJECTROOT = os.path.dirname(os.path.dirname(__file__))
PROVIDER = ["Bangkok",
"Samut Prakarn",
"Nonthaburi",
"Pathum Thani",
"Phra Nakhon Si Ayutthaya",
"Ang Thong",
"Lop Buri",
"Sing Buri",
"Chai Nat",
"Saraburi",
"Chon Buri",
"Rayong",
"Chanthaburi",
"Trat",
"Chachoengsao",
"Prachin Buri",
"Nakhon Nayok",
"Sa kaeo",
"Nakhon Ratchasima",
"Buri Ram",
"Surin",
"Si Sa Ket",
"Ubon Ratchathani",
"Yasothon",
"Chaiyaphum",
"Amnat Charoen",
"Bueng Kan",
"Nong Bua Lam Phu",
"Khon Kaen",
"Udon Thani",
"Loei",
"Nong Khai",
"Maha Sarakham",
"Roi Et",
"Kalasin",
"Sakon Nakhon",
"Nakhon Phanom",
"Mukdahan",
"Chiang Mai",
"Lamphun",
"Lampang",
"Uttaradit",
"Phrae",
"Nan",
"Phayao",
"Chiang Rai",
"Mae Hong Son",
"Nakhon Sawan",
"Uthai Thani",
"Kamphaeng Phet",
"Tak",
"Sukhothai",
"Phitsanulok",
"Phichit",
"Phetchabun",
"Ratchaburi",
"Kanchanaburi",
"Suphan Buri",
"Nakhon Pathom",
"Samut Sakhon",
"Samut Songkhram",
"Phetchaburi",
"Prachuap Khiri Khan",
"Nakhon Si Thammarat",
"Krabi",
"Phang-nga",
"Phuket",
"Surat Thani",
"Ranong",
"Chumphon",
"Songkhla",
"Satun",
"Trang",
"Phatthalung",
"Pattani",
"Yala",
"Narathiwat",
"NakhonSiThammarat",
"Phangnga",
"Ayutthaya",
"Sa Kaeo",
"VoWiFi"]

CHANGEWORD = [
"ค่าบริการข้ามแดนอัตโนมัติ",
"เลขที่ลูกค้า",
"หมายเลขโทรศัพท์",
"หมายเลขผู้ใช้อินเทอร์เน็ต",
"ค่าบริการที่เรียกเก็บ",
"(ต่อ)",
"รายการโทรออกในต่างประเทศ",
"ข้อมูลการใช้บริการโทรศัพท์",
"ข้อมูลการใช้บริการโทรศัพท์ที่ใช้จริง",
"รวมข้อมูลการใช้บริการโทรศัพท์ที่ใช้จริง",
"ภายในเครือข่าย",
"นอกเครือข่าย",
"ค่าใช้บริการที่เรียกเก็บ",
"ค่าโทรส่วนเกินโปรโมชั่น",
"รวมค่าบริการก่อนภาษีมูลค่าเพิ่ม",
"โทรภายในกลุ่ม",
"โทรภายนอกกลุ่ม",
"ค่าใช้บริการเสริม",
"ค่าใช้บริการเสริมอื่นๆ",
"เหมาจ่าย",
"รับสิทธิ์ใช้งาน",
"แพ็กเริ่มต้น",
"โทรทุกเครือข่าย",
"สิทธิพิเศษโทรฟรีเข้า",
"ได้ไม่จำกัด",
"ได้ไม่จำกัดที่ความเร็วสูงสุด",
"อัตราค่าโทร",
"ค่าเช่าหมายเลขรายเดือน",
"ค่า",
"เช่น",
"รับส่งSMSข้อมูล/บันเทิง",
"บริการรับส่งข้อความ",
"เหมาจ่าย",
"บริการส่งข้อความระหว่างประเทศ",
"บาทต่อเดือน"]